### ISSUE TITLE
Simpson's paradox in iris regression

### ISSUE THREAD

**Issue by allisonhorst** [jafflerbach/github_collab#1]
@jafflerbach Need to add grouping for species in regression. Figure created in the chunk beginning:
[line 50](https://github.com/jafflerbach/github_collab/blob/master/docs/manuscript.Rmd#L50).

Within groups should be positive relationship by separate species.

**Comment by jamiecmontgomery** [comment]
Looks right, I'm not able to fix this can you do it? 👩‍💻
